version: '3.8'

services:
  db_alpha:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "otbook"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      TZ: "Europe/Moscow"
    command: --server-id=1

  db_bravo:
    image: mysql:8.0.29
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "otbook"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_TCP_PORT: 3307
      TZ: "Europe/Moscow"
    command: --server-id=2
  
  db_charlie:
    image: mysql:8.0.29
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "otbook"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_TCP_PORT: 3308
      TZ: "Europe/Moscow"
    command: --server-id=3

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080

  backend:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_HOST_1: "db_alpha"
      DB_PORT_1: 3306
      DB_USER_1: "admin"
      DB_PASSWORD_1: "admin"
      DB_NAME_1: "otbook"
      DB_ROLE_1: "master"

      DB_HOST_2: "db_bravo"
      DB_PORT_2: 3307
      DB_USER_2: "admin"
      DB_PASSWORD_2: "admin"
      DB_NAME_2: "otbook"
      DB_ROLE_2: "replica"

      DB_HOST_3: "db_charlie"
      DB_PORT_3: 3308
      DB_USER_3: "admin"
      DB_PASSWORD_3: "admin"
      DB_NAME_3: "otbook"
      DB_ROLE_3: "replica"

    depends_on:
      - db_alpha
      - db_bravo
      - db_charlie
    restart: always

  swagger_ui:
    image: swaggerapi/swagger-ui
    ports:
      - 7000:8080
    environment:
      API_URL: doc/otbook.yaml
    volumes:
      - ./api:/usr/share/nginx/html/doc
