package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/olgoncharov/otbook/internal/usecase/friends/command/delete.friendsRepo -o ./internal/usecase/friends/command/delete/mocks/friends_repo_mock.go -n FriendsRepoMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// FriendsRepoMock implements delete.friendsRepo
type FriendsRepoMock struct {
	t minimock.Tester

	funcDeleteFriend          func(ctx context.Context, user string, friend string) (err error)
	inspectFuncDeleteFriend   func(ctx context.Context, user string, friend string)
	afterDeleteFriendCounter  uint64
	beforeDeleteFriendCounter uint64
	DeleteFriendMock          mFriendsRepoMockDeleteFriend
}

// NewFriendsRepoMock returns a mock for delete.friendsRepo
func NewFriendsRepoMock(t minimock.Tester) *FriendsRepoMock {
	m := &FriendsRepoMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteFriendMock = mFriendsRepoMockDeleteFriend{mock: m}
	m.DeleteFriendMock.callArgs = []*FriendsRepoMockDeleteFriendParams{}

	return m
}

type mFriendsRepoMockDeleteFriend struct {
	mock               *FriendsRepoMock
	defaultExpectation *FriendsRepoMockDeleteFriendExpectation
	expectations       []*FriendsRepoMockDeleteFriendExpectation

	callArgs []*FriendsRepoMockDeleteFriendParams
	mutex    sync.RWMutex
}

// FriendsRepoMockDeleteFriendExpectation specifies expectation struct of the friendsRepo.DeleteFriend
type FriendsRepoMockDeleteFriendExpectation struct {
	mock    *FriendsRepoMock
	params  *FriendsRepoMockDeleteFriendParams
	results *FriendsRepoMockDeleteFriendResults
	Counter uint64
}

// FriendsRepoMockDeleteFriendParams contains parameters of the friendsRepo.DeleteFriend
type FriendsRepoMockDeleteFriendParams struct {
	ctx    context.Context
	user   string
	friend string
}

// FriendsRepoMockDeleteFriendResults contains results of the friendsRepo.DeleteFriend
type FriendsRepoMockDeleteFriendResults struct {
	err error
}

// Expect sets up expected params for friendsRepo.DeleteFriend
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) Expect(ctx context.Context, user string, friend string) *mFriendsRepoMockDeleteFriend {
	if mmDeleteFriend.mock.funcDeleteFriend != nil {
		mmDeleteFriend.mock.t.Fatalf("FriendsRepoMock.DeleteFriend mock is already set by Set")
	}

	if mmDeleteFriend.defaultExpectation == nil {
		mmDeleteFriend.defaultExpectation = &FriendsRepoMockDeleteFriendExpectation{}
	}

	mmDeleteFriend.defaultExpectation.params = &FriendsRepoMockDeleteFriendParams{ctx, user, friend}
	for _, e := range mmDeleteFriend.expectations {
		if minimock.Equal(e.params, mmDeleteFriend.defaultExpectation.params) {
			mmDeleteFriend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteFriend.defaultExpectation.params)
		}
	}

	return mmDeleteFriend
}

// Inspect accepts an inspector function that has same arguments as the friendsRepo.DeleteFriend
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) Inspect(f func(ctx context.Context, user string, friend string)) *mFriendsRepoMockDeleteFriend {
	if mmDeleteFriend.mock.inspectFuncDeleteFriend != nil {
		mmDeleteFriend.mock.t.Fatalf("Inspect function is already set for FriendsRepoMock.DeleteFriend")
	}

	mmDeleteFriend.mock.inspectFuncDeleteFriend = f

	return mmDeleteFriend
}

// Return sets up results that will be returned by friendsRepo.DeleteFriend
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) Return(err error) *FriendsRepoMock {
	if mmDeleteFriend.mock.funcDeleteFriend != nil {
		mmDeleteFriend.mock.t.Fatalf("FriendsRepoMock.DeleteFriend mock is already set by Set")
	}

	if mmDeleteFriend.defaultExpectation == nil {
		mmDeleteFriend.defaultExpectation = &FriendsRepoMockDeleteFriendExpectation{mock: mmDeleteFriend.mock}
	}
	mmDeleteFriend.defaultExpectation.results = &FriendsRepoMockDeleteFriendResults{err}
	return mmDeleteFriend.mock
}

//Set uses given function f to mock the friendsRepo.DeleteFriend method
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) Set(f func(ctx context.Context, user string, friend string) (err error)) *FriendsRepoMock {
	if mmDeleteFriend.defaultExpectation != nil {
		mmDeleteFriend.mock.t.Fatalf("Default expectation is already set for the friendsRepo.DeleteFriend method")
	}

	if len(mmDeleteFriend.expectations) > 0 {
		mmDeleteFriend.mock.t.Fatalf("Some expectations are already set for the friendsRepo.DeleteFriend method")
	}

	mmDeleteFriend.mock.funcDeleteFriend = f
	return mmDeleteFriend.mock
}

// When sets expectation for the friendsRepo.DeleteFriend which will trigger the result defined by the following
// Then helper
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) When(ctx context.Context, user string, friend string) *FriendsRepoMockDeleteFriendExpectation {
	if mmDeleteFriend.mock.funcDeleteFriend != nil {
		mmDeleteFriend.mock.t.Fatalf("FriendsRepoMock.DeleteFriend mock is already set by Set")
	}

	expectation := &FriendsRepoMockDeleteFriendExpectation{
		mock:   mmDeleteFriend.mock,
		params: &FriendsRepoMockDeleteFriendParams{ctx, user, friend},
	}
	mmDeleteFriend.expectations = append(mmDeleteFriend.expectations, expectation)
	return expectation
}

// Then sets up friendsRepo.DeleteFriend return parameters for the expectation previously defined by the When method
func (e *FriendsRepoMockDeleteFriendExpectation) Then(err error) *FriendsRepoMock {
	e.results = &FriendsRepoMockDeleteFriendResults{err}
	return e.mock
}

// DeleteFriend implements delete.friendsRepo
func (mmDeleteFriend *FriendsRepoMock) DeleteFriend(ctx context.Context, user string, friend string) (err error) {
	mm_atomic.AddUint64(&mmDeleteFriend.beforeDeleteFriendCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteFriend.afterDeleteFriendCounter, 1)

	if mmDeleteFriend.inspectFuncDeleteFriend != nil {
		mmDeleteFriend.inspectFuncDeleteFriend(ctx, user, friend)
	}

	mm_params := &FriendsRepoMockDeleteFriendParams{ctx, user, friend}

	// Record call args
	mmDeleteFriend.DeleteFriendMock.mutex.Lock()
	mmDeleteFriend.DeleteFriendMock.callArgs = append(mmDeleteFriend.DeleteFriendMock.callArgs, mm_params)
	mmDeleteFriend.DeleteFriendMock.mutex.Unlock()

	for _, e := range mmDeleteFriend.DeleteFriendMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteFriend.DeleteFriendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteFriend.DeleteFriendMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteFriend.DeleteFriendMock.defaultExpectation.params
		mm_got := FriendsRepoMockDeleteFriendParams{ctx, user, friend}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteFriend.t.Errorf("FriendsRepoMock.DeleteFriend got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteFriend.DeleteFriendMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteFriend.t.Fatal("No results are set for the FriendsRepoMock.DeleteFriend")
		}
		return (*mm_results).err
	}
	if mmDeleteFriend.funcDeleteFriend != nil {
		return mmDeleteFriend.funcDeleteFriend(ctx, user, friend)
	}
	mmDeleteFriend.t.Fatalf("Unexpected call to FriendsRepoMock.DeleteFriend. %v %v %v", ctx, user, friend)
	return
}

// DeleteFriendAfterCounter returns a count of finished FriendsRepoMock.DeleteFriend invocations
func (mmDeleteFriend *FriendsRepoMock) DeleteFriendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFriend.afterDeleteFriendCounter)
}

// DeleteFriendBeforeCounter returns a count of FriendsRepoMock.DeleteFriend invocations
func (mmDeleteFriend *FriendsRepoMock) DeleteFriendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFriend.beforeDeleteFriendCounter)
}

// Calls returns a list of arguments used in each call to FriendsRepoMock.DeleteFriend.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteFriend *mFriendsRepoMockDeleteFriend) Calls() []*FriendsRepoMockDeleteFriendParams {
	mmDeleteFriend.mutex.RLock()

	argCopy := make([]*FriendsRepoMockDeleteFriendParams, len(mmDeleteFriend.callArgs))
	copy(argCopy, mmDeleteFriend.callArgs)

	mmDeleteFriend.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteFriendDone returns true if the count of the DeleteFriend invocations corresponds
// the number of defined expectations
func (m *FriendsRepoMock) MinimockDeleteFriendDone() bool {
	for _, e := range m.DeleteFriendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteFriendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDeleteFriendCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteFriend != nil && mm_atomic.LoadUint64(&m.afterDeleteFriendCounter) < 1 {
		return false
	}
	return true
}

// MinimockDeleteFriendInspect logs each unmet expectation
func (m *FriendsRepoMock) MinimockDeleteFriendInspect() {
	for _, e := range m.DeleteFriendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to FriendsRepoMock.DeleteFriend with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteFriendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterDeleteFriendCounter) < 1 {
		if m.DeleteFriendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to FriendsRepoMock.DeleteFriend")
		} else {
			m.t.Errorf("Expected call to FriendsRepoMock.DeleteFriend with params: %#v", *m.DeleteFriendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteFriend != nil && mm_atomic.LoadUint64(&m.afterDeleteFriendCounter) < 1 {
		m.t.Error("Expected call to FriendsRepoMock.DeleteFriend")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *FriendsRepoMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockDeleteFriendInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *FriendsRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *FriendsRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteFriendDone()
}
