database:
  - host: "localhost"
    port: "3306"
    user: "admin"
    password: "admin"
    db_name: "otbook"
    role: master

  - host: "localhost"
    port: "3307"
    user: "admin"
    password: "admin"
    db_name: "otbook"
    role: replica

  - host: "localhost"
    port: "3308"
    user: "admin"
    password: "admin"
    db_name: "otbook"
    role: replica

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

jwt:
  access_token_ttl: 3600
  refresh_token_ttl: 108000
  signing_key: nnUdOVjyvgtsTUPguUrm

password:
  hash_generation_cost: 5

http:
  server_addr: ":8000"

feed:
  limit: 1000
  is_cache_disabled: false
